version: '3.7'
services:
  postgres:
    image: postgres:11
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: filters
      POSTGRES_USER: filters
      POSTGRES_PASSWORD: filters
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: null